
package vue;

import facade.GestionParkVoitures;

/**
 * class Acceuil.
 * @author Boubacar
 */
public class Accueil extends javax.swing.JFrame implements Vue {

  /**
   * Creates new form Accueil.
   */
  facade.GestionParkVoitures facade;

  /**
   * acceuil.
   * @param facade la facade.
   */
  public Accueil(facade.GestionParkVoitures facade) {
    this.facade = facade;
    facade.register(this);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setLayout(null);

    jButton1.setText("Creer Voiture");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton1);
    jButton1.setBounds(22, 20, 126, 29);

    jButton2.setText("Liste voitures");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton2);
    jButton2.setBounds(22, 76, 129, 29);

    jLabel1.setIcon(new javax.swing.ImageIcon
        ("/Users/lastking24/Downloads/parcImages/tesla-model-x.jpg")); // NOI18N
    jLabel1.setText("jLabel1");
    jPanel1.add(jLabel1);
    jLabel1.setBounds(-25, -66, 1015, 406);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
            layout.createSequentialGroup().addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                696, Short.MAX_VALUE).addContainerGap()));
    layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup().addGap(17, 17, 17)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                329, Short.MAX_VALUE).addContainerGap()));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    CreerVoiture creerVoiture = new CreerVoiture(this.facade);
    creerVoiture.setVisible(true);
    this.setVisible(false);

  }// GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
    ListVoiture listeVoiture = new ListVoiture(this.facade);
    listeVoiture.setVisible(true);
    this.setVisible(false);
  }// GEN-LAST:event_jButton2ActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables

  @Override
  public void update(GestionParkVoitures facede) {
    this.facade = facede;
  }
}
