
package vue;

import facade.GestionParkVoitures;

/**
 *class CreerVoitureInput.
 * @author Boubacar
 */
public class CreerVoitureInput extends javax.swing.JFrame implements Vue {

  /**
   * Creates new form CreerVoitureInput.
   */
  GestionParkVoitures facade;

  /**
   * constructeur.
   * @param facade facade/
   */
  public CreerVoitureInput(GestionParkVoitures facade) {
    this.facade = facade;
    facade.register(this);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    marqueVoiture = new javax.swing.JTextField();
    ModeleVoiture = new javax.swing.JTextField();
    NumeroSerieVoiture = new javax.swing.JTextField();
    LargeurPneu = new javax.swing.JTextField();
    Hauteur = new javax.swing.JTextField();
    HiverPneu = new javax.swing.JComboBox<>();
    marquePneu = new javax.swing.JTextField();
    jBajouterVoiture = new javax.swing.JButton();
    jLabel9 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setText("Marque");

    jLabel2.setText("Modele");

    jLabel3.setText("Numero Serie Moteur : ");

    jLabel4.setText("Pneu Caractéristiques:");

    jLabel5.setText("Largeur : ");

    jLabel6.setText("Hauteur:");

    jLabel7.setText("Hiver :");

    jLabel8.setText("Marque :");

    marqueVoiture.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        marqueVoitureActionPerformed(evt);
      }
    });

    ModeleVoiture.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ModeleVoitureActionPerformed(evt);
      }
    });

    NumeroSerieVoiture.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        NumeroSerieVoitureActionPerformed(evt);
      }
    });

    HiverPneu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "false", "true" }));
    HiverPneu.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        HiverPneuActionPerformed(evt);
      }
    });

    jBajouterVoiture.setText("Ajouter");
    jBajouterVoiture.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBajouterVoitureActionPerformed(evt);
      }
    });

    jLabel9.setText("Ajouter une nouvelle voiture");

    jButton1.setText("List");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
            jPanel1Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(jButton1)
                .addGap(83, 83, 83).addComponent(jBajouterVoiture).addGap(73, 73, 73))
        .addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
            .createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout.createSequentialGroup()
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                jPanel1Layout.createSequentialGroup().addGap(92, 92, 92).addGroup(jPanel1Layout
                                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup().addGap(114, 114, 114)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING,
                                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING,
                                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING,
                                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup().addGap(93, 93, 93).addGroup(
                            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(marqueVoiture).addComponent(ModeleVoiture)
                                .addComponent(NumeroSerieVoiture).addComponent(LargeurPneu).addComponent(Hauteur)
                                .addComponent(HiverPneu, 0, 126, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                            jPanel1Layout.createSequentialGroup().addGap(99, 99, 99).addComponent(marquePneu,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup().addGap(127, 127, 127).addComponent(jLabel9,
                javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(170, Short.MAX_VALUE)));
    jPanel1Layout
        .setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup().addGap(24, 24, 24).addComponent(jLabel9).addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1).addComponent(marqueVoiture, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2).addComponent(ModeleVoiture, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3).addComponent(NumeroSerieVoiture, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18).addComponent(jLabel4).addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5).addComponent(LargeurPneu, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6).addComponent(Hauteur, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7).addComponent(HiverPneu, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8).addComponent(marquePneu, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBajouterVoiture).addComponent(jButton1))));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
        jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel1,
        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void marqueVoitureActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_marqueVoitureActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_marqueVoitureActionPerformed

  private void ModeleVoitureActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ModeleVoitureActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_ModeleVoitureActionPerformed

  private void NumeroSerieVoitureActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NumeroSerieVoitureActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_NumeroSerieVoitureActionPerformed

  private void HiverPneuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_HiverPneuActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_HiverPneuActionPerformed

  private void jBajouterVoitureActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBajouterVoitureActionPerformed
    // TODO add your handling code here:
    String marqueVoitureString = marqueVoiture.getText();
    String modeleVoitureString = ModeleVoiture.getText();
    int numeroSerieMoteur = Integer.parseInt(NumeroSerieVoiture.getText());
    int indexSelectedHiver = HiverPneu.getSelectedIndex();
    Boolean isHiver = new Boolean((HiverPneu.getItemAt(indexSelectedHiver)).toString());
    Double largeur = Double.parseDouble(LargeurPneu.getText());
    Double hauteur = Double.parseDouble(Hauteur.getText());
    String marquePneuString = marquePneu.getText();
    facade.creerVoiture(marqueVoitureString, modeleVoitureString, numeroSerieMoteur, largeur, hauteur, marquePneuString,isHiver);
    // facade.creerVoiture(marqueVoitureString, modeleVoitureString,
    // numeroSerieMoteur, largeur, hauteur, marquePneuString);
    facade.afficherListPneux();
    clearInput();
  }// GEN-LAST:event_jBajouterVoitureActionPerformed

  public void clearInput() {
    marqueVoiture.setText("");
    ModeleVoiture.setText("");
    NumeroSerieVoiture.setText("");
    LargeurPneu.setText("");
    Hauteur.setText("");
    marquePneu.setText("");
  }

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

    ListVoiture listVoiture = new ListVoiture(this.facade);
    listVoiture.setVisible(Boolean.TRUE);
    this.setVisible(false);

  }// GEN-LAST:event_jButton1ActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField Hauteur;
  private javax.swing.JComboBox<String> HiverPneu;
  private javax.swing.JTextField LargeurPneu;
  private javax.swing.JTextField ModeleVoiture;
  private javax.swing.JTextField NumeroSerieVoiture;
  private javax.swing.JButton jBajouterVoiture;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextField marquePneu;
  private javax.swing.JTextField marqueVoiture;
  // End of variables declaration//GEN-END:variables

  @Override
  public void update(GestionParkVoitures facede) {
    this.facade = facede;
  }
}
